name: myenv
channels:
  - conda-forge
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/rapidsai
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.10
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libexpat=2.6.3
  - libffi=3.4.2
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pure_eval=0.2.3
  - python=3.11.10
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
#  - pywin32=307
  - pyzmq=26.3.0
  - setuptools=74.1.2
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
#  - ucrt=10.0.22621.0
#  - vc=14.3
#  - vc14_runtime=14.40.33810
#  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.2.6
  - zeromq=4.3.5
  - pip:
      - apscheduler==3.11.0
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - arch==7.0.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - base58==2.1.1
      - based58==0.1.1
      - beautifulsoup4==4.12.3
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - ciso8601==2.3.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.0.11
      - discord-py==2.4.0
      - filelock==3.4.1
      - filterpy==1.4.5
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozendict==2.4.4
      - frozenlist==1.5.0
      - fugle-marketdata==2.2.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.2
      - h11==0.14.0
      - h5py==3.12.1
      - html5lib==1.1
      - hurst==0.0.5
      - idna==3.10
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - keras==3.6.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - loguru==0.6.0
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - maturin==1.7.1
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - multitasking==0.0.11
      - namex==0.0.8
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.13.0
      - orjson==3.10.7
      - outcome==1.3.0.post0
      - packaging==24.1
      - pandas==2.2.2
      - patsy==0.5.6
      - peewee==3.17.6
      - pillow==10.4.0
      - pmdarima==2.0.4
      - propcache==0.2.0
      - protobuf==4.25.5
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydot==3.0.2
      - pyee==11.1.1
      - pygments==2.18.0
      - pynacl==1.5.0
      - pyparsing==3.1.4
      - pyrsca==0.1.1
      - pysocks==1.7.1
      - pysolace==0.9.40
      - python-dotenv==1.0.1
#      - python-graphviz==0.20.3
      - pytz==2024.2
      - redis==5.2.0
      - requests==2.32.3
      - rich==13.9.2
      - rust==0.1.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - selenium==4.27.1
      - sentry-sdk==1.5.12
      - shioaji==1.2.4
      - six==1.16.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - statsmodels==0.14.3
#      - ta-lib==0.4.32
#      - tensorboard==2.17.1
#      - tensorboard-data-server==0.7.2
#      - tensorflow==2.17.0
#      - tensorflow-intel==2.17.0
#      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - trio==0.28.0
      - trio-websocket==0.11.1
      - tzdata==2024.1
      - urllib3==2.2.3
      - webdriver-manager==4.0.2
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.4
      - win32-setctime==1.1.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yarl==1.17.1
      - yfinance==0.2.54
      - zipp==3.20.2

